// Code generated by mockery 2.53.0. DO NOT EDIT.

package repository

import mock "github.com/stretchr/testify/mock"

// MockAlphabetRepository is an autogenerated mock type for the AlphabetRepository type
type MockAlphabetRepository struct {
	mock.Mock
}

type MockAlphabetRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAlphabetRepository) EXPECT() *MockAlphabetRepository_Expecter {
	return &MockAlphabetRepository_Expecter{mock: &_m.Mock}
}

// Get provides a mock function with given fields: name
func (_m *MockAlphabetRepository) Get(name string) (string, error) {
	ret := _m.Called(name)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (string, error)); ok {
		return rf(name)
	}
	if rf, ok := ret.Get(0).(func(string) string); ok {
		r0 = rf(name)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(name)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAlphabetRepository_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockAlphabetRepository_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - name string
func (_e *MockAlphabetRepository_Expecter) Get(name interface{}) *MockAlphabetRepository_Get_Call {
	return &MockAlphabetRepository_Get_Call{Call: _e.mock.On("Get", name)}
}

func (_c *MockAlphabetRepository_Get_Call) Run(run func(name string)) *MockAlphabetRepository_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockAlphabetRepository_Get_Call) Return(_a0 string, _a1 error) *MockAlphabetRepository_Get_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAlphabetRepository_Get_Call) RunAndReturn(run func(string) (string, error)) *MockAlphabetRepository_Get_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockAlphabetRepository creates a new instance of MockAlphabetRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAlphabetRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAlphabetRepository {
	mock := &MockAlphabetRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
